### PR TITLE
Seo improvement

### PR DESCRIPTION
**Pull request by andipavllo**
@masahirotanaka when you have time, please take a look at this. Here are the changes:

* Minor fixes to CSS defer-load.
* Added Grunt `imagemin ` task to optimize images, using default value for optimization.
* Added Grunt `cssmin` task to minify CSS.
* Fixed Grunt `uglify` task in order to uglify vendor's not minified JS.
* Fixed Grunt `copy` task for some vendor's CSS/JS.

### CODE REVIEW

**Comment by masahirotanaka** [comment]
@andipavllo Thanks! I'd like to ask you to include this in `dev_add_logic` branch. `dev_add_logic` is pending to release in this week. Can you checkout `dev_add_logic` and see if your change can be merged and running correctly?

After that, please create PR again asking to merge to dev_add_logic branch.

**Comment by andipavllo** [comment]
@masahirotanaka as `dev_addlogic` has already been merged, I just fixed the conflict. I tested it with the new changes and it seems running correctly.

**Comment by masahirotanaka** [comment]
Thanks @andipavllo . I merged the branch.
One thing I noticed is it generates `codemirror.css` and `style.css` in the root directory.
I think this is a wrong behavior, but I am not sure if this happens after this modification.
Please check and fix as necessary.

**Comment by andipavllo** [comment]
@masahirotanaka fixed here

https://github.com/monaca/website/commit/cf4b013b689642addfa978505c916f3a1742c028

**Pull request merged**
